default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

  database: <%#= ENV['DB_NAME'] %>
  username: <%#= ENV['DB_USER'] %>
  password: <%#= ENV['DB_PASSWORD'] %>
  host: <%#= ENV['DB_HOST'] %>
  port: 3306

development:
  <<: *default

test:
  <<: *default


production:
  <<: *default