version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: db-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_system_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - chat_system_vol:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.4.0-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - chat_system_redis_vol:/data

  redis-insight:
    image: redis/redisinsight:2.54
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      - redis
    
  rabbitmq:
    image: rabbitmq:4.0-rc-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: elasticsearch:8.15.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      # To resolve virtual memory allocation limits on startup
      - discovery.type=single-node
    volumes:
      - chat_system_es_vol:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.15.1
    container_name: kibana
    ports:
      - "5601:5601"

    

volumes:
  chat_system_vol:
    driver: local
  chat_system_redis_vol:
    driver: local
  chat_system_es_vol:
    driver: local